name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake gif
        uses: Platane/snk@v3
        with:
          github_user_name: Nadirmermer
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake.gif

      - name: Pull before commit (önce uzak branch'i al)
        run: git pull origin main --rebase

      - name: Push the snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "update contribution snake"
          add: "*.svg *.gif"
